languageCode: en-us
title: anirudhb
baseURL: https://www.ani-b.me
copyright: Ani B © {year}
params:
  description: Making the things that help other people make things. Masters student at
    WBS passionate about data, products, Economics and Entrepreneurship.
  github: anirudh-cloud
  sitename: ani-b
  twitter: ani_thoughts
menu:
  main:
    - identifier: home
      name: home
      title: Home
      url: /
      weight: '25'
    - identifier: about
      name: about me
      title: About
      url: /about
      weight: '30'
    - identifier: blog
      name: blog
      title: Blog
      url: /blog
      weight: '100'
    - identifier: linkedin
      name: linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/b-anirudh
      weight: '50'
    - identifier: products
      name: products
      title: Products
      url: /s/products
      weight: '50'
    - identifier: resume
      name: resume
      preserveTaxonomyNames: yes
      title: Resume
      url: /AnirudhB_resume_25Jul_2021.pdf
      weight: '50'

preserveTaxonomyNames: true
disableToc: 'false'
taxonomies:
  tag: tags
markup:
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: yes
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    parser:
      attribute: yes
      autoHeadingID: yes
      autoHeadingIDType: github
    renderer:
      hardWraps: no
      unsafe: yes
      xhtml: no
